src/Entity/Image.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ImageRepository")
 */
class Image
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $path;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $img_path;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $alt;

    /**
     * @Assert\File(mimeTypes={ "application/pdf", "application/x-pdf", "image/jpg", "image/png", "image/jpeg", "image/gif"})
     */
    private $file;

    public function getFile()
    {
        return $this->file;
    }

    public function setFile($file)
    {
        $this->file = $file;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getImgPath(): ?string
    {
        return $this->img_path;
    }

    public function setImgPath(string $img_path): self
    {
        $this->img_path = $img_path;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->alt;
    }

    public function setAlt(?string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }
}

src/Entity/Task.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 */
class Task
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $done;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", cascade={"persist", "remove"})
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Priority")
     * @ORM\JoinColumn(nullable=false)
     */
    private $priority;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="tasks")
     */
    private $categories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDone(): ?bool
    {
        return $this->done;
    }

    public function setDone(?bool $done): self
    {
        $this->done = $done;

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPriority(): ?Priority
    {
        return $this->priority;
    }

    public function setPriority(?Priority $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    /**
     * @return Collection|categories[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $taskCategory): self
    {
        if (!$this->categories->contains($taskCategory)) {
            $this->categories[] = $taskCategory;
            $taskCategory->addTask($this);
        }

        return $this;
    }

    public function removeCategory(Category $taskCategory): self
    {
        if ($this->categories->contains($taskCategory)) {
            $this->categories->removeElement($taskCategory);
            $taskCategory->removeTask($this);
        }

        return $this;
    }

}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use App\Entity\Priority;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Form\ImageType;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('done')
            ->add('priority',EntityType::class, array(
                'class' => Priority::class,
                'choice_label' => function($priority){
                    return $priority->getName();
                }

            ))
            ->add('image',ImageType::Class)

            ->add('categories', null, [
                'expanded'    => true,
                'multiple' => true
    ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Form\TaskType;
use App\Repository\TaskRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\FileType;

/**
 * @Route("/task", host="exotest.fr")
 */
class TaskController extends AbstractController
{
    /**
     * @Route("/", name="task_index", methods={"GET"})
     */
    public function index(TaskRepository $taskRepository): Response
    {
        return $this->render('task/index.html.twig', [
            'tasks' => $taskRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="task_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */

            $entityManager = $this->getDoctrine()->getManager();
            $image =$task->getImage();
            $file = $form->get('image')->get('file')->getData();

            if ($file) {

                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('image_abs_path'),$fileName

                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                $image->setPath($this->getParameter('image_abs_path') . '/' . $fileName);
                $image->setImgPath($this->getParameter('image_path') . '/' . $fileName);
                $entityManager->persist($image);
            }
            else {
                $task->setImage(null);
            }
            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirectToRoute('task_index');

        }
        return $this->render('task/new.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="task_show", methods={"GET"})
     */
    public function show(Task $task): Response
    {
        return $this->render('task/show.html.twig', [
            'task' => $task,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="task_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Task $task): Response
    {
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $image =$task->getImage();
            $file =$form->get('image')->get('file')->getData();

            if($file) {
                $fileName = $this->generateUniquefileName().'.'.$file->guessExtension();

                try {
                    $file->move(
                        $this->getParameter('image_abs_path'),
                        $fileName
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $this->removeFile($image->getPath());
                $image->setPath($this->getParameter('image_abs_path').'/'.$fileName);
                $image->setImgPath($this->getParameter('image_path').'/'.$fileName);
                $entityManager->persist($image);
            }

            if(empty($image->getId()) && !$file ){
                $task->setImage(null);
            }



            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('task_index', [
                'id' => $task->getId(),
            ]);
        }

        return $this->render('task/edit.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="task_img_delete", methods={"POST"})
     */
    public function deleteImg(Request $request, Task $task): Response
    {
        if ($this->isCsrfTokenValid('delete'.$task->getId(), $request->request->get('_token'))) {
            $image = $task->getImage();
            if($image){
                $this->removeFile($image->getPath());
            }

            $task->setImage(null);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($image);
            $task->setImage(null);
            $entityManager->persist($task);
            $entityManager->flush();
        }

        return $this->redirectToRoute('task_edit', array('id'=>$task->getId()));
    }

    /**
     * @Route("/{id}", name="task_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Task $task): Response
    {
        if ($this->isCsrfTokenValid('delete'.$task->getId(), $request->request->get('_token'))) {
            $image = $task->getImage();
            if($image){
                $this->removeFile($image->getPath());
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($task);
            $entityManager->flush();
        }

        return $this->redirectToRoute('task_index');
    }

    /**
     * @return string
     */
    function generateUniqueFileName() {

        return md5(uniqid());
    }

    private function removeFile($path){
        if(file_exists($path)){
            unlink($path);
        }
    }
}

templates/task/_delete_form.html.twig
<form method="post" action="{{ path('task_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn">Delete</button>
</form>

templates/task/_delete_img_form.html.twig
<form method="post" action="{{ path('task_img_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="POST">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn">Delete</button>
</form>

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Task{% endblock %}

{% block body %}
    <h1>Edit Task</h1>
    {% if task.image %}

        <img src="{{ asset(task.image.imgPath) }}" width="200px" />
        {{ include('task/_delete_img_form.html.twig') }}
    {% endif %}
    {{ include('task/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('task_index') }}">back to list</a>

    {{ include('task/_delete_form.html.twig') }}
{% endblock %}

templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task index{% endblock %}

{% block body %}
    <div class="container col-12 align-self-center"><h1>TASK</h1></div>
    <br>
    <br>
    <div>
        <a href="{{ path('task_index') }}" class="btn btn-dark btn-lg active" role="button" title="Task">Task</a>
        <a href="{{ path('priority_index') }}" class="btn btn-dark btn-lg active" role="button" title="Priority">Priority</a>
        <a href="{{ path('image_index') }}" class="btn btn-dark btn-lg active" role="button" title="Image">Image</a>
        <a href="{{ path('category_index') }}" class="btn btn-dark btn-lg active" role="button" title="Category">Category</a>
        <a href="{{ path('tasklist_index') }}" class="btn btn-dark btn-lg active" role="button" title="Tasklist">Tasklist</a>
        <a href="{{ path('listitem_index') }}" class="btn btn-dark btn-lg active" role="button" title="Listitem">Listitem</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Done</th>
                <th>Images</th>
                <th>Priority</th>
                <th>Category</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.id }}</td>
                <td>{{ task.name }}</td>
                <td>{{ task.done ? 'Yes' : 'No' }}</td>
                <td>{% if task.image %}

                    <img src="{{ asset(task.image.imgPath) }}" width="200px" />
                    {% endif %}</td>
                <td>{{ task.priority.name }}</td>

                <td>{% for category in task.categories %}
                        {{ category }}
                    {% endfor %}
                </td>
                <td>
                    <a href="{{ path('task_show', {'id': task.id}) }}">show</a>
                    <a href="{{ path('task_edit', {'id': task.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('task_new') }}">Create new</a>
{% endblock %}

templates/task/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Task{% endblock %}

{% block body %}
    <h1>Create new Task</h1>

    {{ include('task/_form.html.twig') }}

    <a href="{{ path('task_index') }}">back to list</a>
{% endblock %}

templates/task/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task{% endblock %}

{% block body %}
    <h1>Task</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ task.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ task.name }}</td>
            </tr>
            <tr>
                <th>Priority</th>
                <td>{{ task.priority.name }}</td>
                <td>{% if task.image %}

                        <img src="{{ asset(task.image.imgPath) }}" width="200px" />
                    {% endif %}</td>
            </tr>
            <tr>
                <th>Done</th>
                <td>{{ task.done ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('task_index') }}">back to list</a>

    <a href="{{ path('task_edit', {'id': task.id}) }}">edit</a>

    {{ include('task/_delete_form.html.twig') }}
{% endblock %}